- hosts: webpagetest-private
  sudo: yes
  vars:
    host_name: wpt.padumts.dropit.in
    port_no: 80
    wpt_version: 2.16
    www_owner: padumts
    www_group: www-data
  roles:
    - webpagetest
    - webpagetest-agent

  pre_tasks:
    - name: be sure apt packages are installed
      apt: >
        name={{ item }}
        state=present
      with_items:
        - php5-gd
        - php5-curl
        - php-apc
        - ffmpeg
        - imagemagick
        - libimage-exiftool-perl
        - libjpeg-progs
      when: ansible_os_family == 'Debian'
