- hosts: webpagetest-private
  sudo: yes
  vars:
    host_name: wpt.padumts.dropit.in
    port_no: 8080
    wpt_version: 2.16
    www_owner: padumts
    www_group: www-data
  roles:
    - webpagetest
    - webpagetest-agent